### ISSUE TITLE
Please add support for a new proposed microdata property (itemprop-reverse)

### ISSUE THREAD

**Issue by jvandriel** [yoichiro/semantic_inspector#3]
Hi @yoichiro,

My name is Jarno van Driel, Semantic SEO and contributor to the further development of schema.org over at the schema.org community group: https://www.w3.org/community/schemaorg/

I would like to ask you if could add support to your extension for a new proposed microdata attribute: @itemprop-reverse.

This attribute does more or less the same as the @itemprop only in reversed order.
More details about this property can be read on: http://www.w3.org/wiki/WebSchemas/InverseProperties

The reason why I ask if you would consider adding support for it, is because of the approval process over at the W3. For this property to get accepted by the W3 and added to the microdata specs, we (the folks behind the proposal) need to show there are multiple tools out there that are able to consume this property.

First to support this new property upfront are the Structured Data Linter: http://linter.structured-data.org/ and META SEO inspector: https://chrome.google.com/webstore/detail/microdatareveal/olapakiakkblfdaajcifgldandnikpdh/support, but unfortunately these aren't enough to build a proper case yet.

And hence my message to you.

Hoping to hear from you,
Jarno van Driel

**Comment by yoichiro** [comment]
@jvandriel I see, I intend to support the new attribute @itemprop-reverse in  this extension. Well, could you provide some test pages which have @itemprop-reverse attributes?

**Comment by yoichiro** [comment]
@jvandriel I have just released the new version 1.2.0. It includes the @itemprop-reverse support. The diff is #4.

**Comment by jvandriel** [comment]
Hi Yoichiro,

First off, thank you very much for being willing to build in support for
the new itemprop-reverse attribute.

Now I'm a bit uncertain about how you show the itemprop-reverse attribute's
values/connection but I'm guessing you're indicating the attribute by means
of the yellow marker (containing a 'R'), am I right with this?

If so be aware that your current output might be a bit confusing for users.
If you look at the Structured Data Linter's (SDL output of 2 example pages
you'll see how the markup should be understood:

   -
   http://linter.structured-data.org/?url=http:%2F%2Fwww.omiod.com%2Fchrome-extensions%2Fmeta-seo-inspector%2Ftest%2F3.htm
   -
   http://linter.structured-data.org/?url=http:%2F%2Fwww.omiod.com%2Fchrome-extensions%2Fmeta-seo-inspector%2Ftest%2F4.htm

In both examples the SDL result shows that Subject and Object reverse their
position in the graph, meaning in case of example 1 (
http://www.omiod.com/chrome-extensions/meta-seo-inspector/test/3.htm) the
Freebase item should be the top level entity and the Brand should be nested
within it.

In the second example (
http://www.omiod.com/chrome-extensions/meta-seo-inspector/test/4.htm) there
should be 2 top-level entites (Bakery and Restaurant) which both contain a
nested ShoppingCenter.

If you run the below RDFa version through Google's Structured Data Testing
Tool https://developers.google.com/structured-data/testing-tool/ you'll
see what I mean:

<html>
<head>
<title>Test 4 - rev</title>
</head>
<body vocab="http://schema.org/">

<h1>Example of rev usage.</h1>

<p>Linking from a shopping mall to the businesses contained</p>

<div typeof="ShoppingCenter">
<span property="name">The ACME Shopping Mall on Structured Data
Avenue</span>
<span property="description">The ACME Shopping Mall is your one-stop
paradise for all data-related shopping needs, from schemas to instance
data</span>
<p>Here is a list of shops inside:</p>
<div rev="containedIn" typeof="Restaurant">
<span property="name">Dan Brickley's Data Restaurant</span>
</div>

<div rev="containedIn" typeof="Bakery">
<span property="name">Ramanathan Guha's Meta Content Framework Bakery</span>
</div>

</div>

<p>
<a href="/chrome-extensions/meta-seo-inspector/test/">back</a>
</p>

</body>
</html>

I hope this helps, and please, don't be shy to contact me if you need
further assistance.

Greets,
Jarno

2015-04-14 2:23 GMT+02:00 Yoichiro Tanaka notifications@github.com:

**Comment by yoichiro** [comment]
@jvandriel As the result, how should I fix my application? I could not understand your opinion.

**Comment by jvandriel** [comment]
How about this (I've noted it down the way the semantic inspector currently
indicates types, properties and any nested types and properties):
- _The output for
  http://www.omiod.com/chrome-extensions/meta-seo-inspector/test/3.htm
  http://www.omiod.com/chrome-extensions/meta-seo-inspector/test/3.htm
  should be (1 top level entity):_

_I:_ http://www.freebase.com/m/04sv4
_P:_ brand
_I:_ http://schema.org/Brand
_P:_ name
Lumia
- _The output for
  http://www.omiod.com/chrome-extensions/meta-seo-inspector/test/4.htm
  http://www.omiod.com/chrome-extensions/meta-seo-inspector/test/4.htm
  should be (2 top level entities):_

_I:_ http://schema.org/Restaurant
_P:_ name
Dan Brickley's Data Restaurant
_P:_ containedIn
_I:_ http://schema.org/ShoppingCenter
_P:_ name
The ACME Shopping Mall on Structured Data Avenue
_P:_ description
The ACME Shopping Mall is your one-stop paradise for all data-related
shopping needs, from schemas to instance data

_I:_ http://schema.org/Bakery
_P:_ name
Ramanathan Guha's Meta Content Framework Bakery
_P:_ containedIn
_I:_ http://schema.org/ShoppingCenter
_P:_ name
The ACME Shopping Mall on Structured Data Avenue
_P:_ description
The ACME Shopping Mall is your one-stop paradise for all data-related
shopping needs, from schemas to instance data

If you need any further help, simply let me know.

2015-04-14 12:57 GMT+02:00 Yoichiro Tanaka notifications@github.com:

**Comment by yoichiro** [comment]
@jvandriel I'm waiting the pull request from you.

**Comment by jvandriel** [comment]
eh, do you imply that I program the change?

If so I'm afraid I have to disappoint you as I have absolutely no
programming skills. However, if you need help fixing this I could ask
around if somebody's willing to help from the Google+ community Semantic
Search Marketing
https://plus.google.com/u/0/communities/103048251221048356778 (which I
moderate).

2015-04-16 2:13 GMT+02:00 Yoichiro Tanaka notifications@github.com:

**Comment by yoichiro** [comment]
@jvandriel Sorry, I want to use my time to develop other applications currently...

**Comment by yoichiro** [comment]
Closed.
